# HTTP 400
INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT"
IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
NO_FACE_DETECTED = "NO_FACE_DETECTED"
LOW_QUALITY_IMAGE = "LOW_QUALITY_IMAGE"

# HTTP 401
TOKEN_EXPIRED = "TOKEN_EXPIRED"
INVALID_TOKEN = "INVALID_TOKEN"

# HTTP 403
FORBIDDEN = "FORBIDDEN"

# HTTP 404
RESULT_NOT_FOUND = "RESULT_NOT_FOUND"
USER_NOT_FOUND = "USER_NOT_FOUND"

# HTTP 409
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

# HTTP 422
VALIDATION_ERROR = "VALIDATION_ERROR"

# HTTP 429
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

# HTTP 500
ML_INFERENCE_FAILED = "ML_INFERENCE_FAILED"

# HTTP 503
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"